name: build app
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: "inserisci il nome della branch"

jobs: 
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repository code
        uses: actions/checkout@v3
        
      - name: setup node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x
      - name: install npm
        run: npm install

      - name: run with npm
        run: npm run build
  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout repository cod
        uses: actions/checkout@v3

      - name: npm install
        run: npm intstall

      - name: test
        run: npm run test
        
