name: build app
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: "inserisci il nome della branch"

jobs: 
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repository code
        uses: actions/checkout@v3
        
      - name: setup node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x
      - name: install npm
        run: npm install

      - name: run with npm
        run: npm run build
  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout repository cod
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment: 
      name: production
      url:  ${{ steps.deployment.outputs.page_url }}

    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: use node.js
        uses: actions/configure-pages@v3
        with:
          node-version: 18.x

      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - run: npm install
      - run: npm run build

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: ":/out"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
    
        
